---
abstract: 'use dh-make-perl to generate .deb archives from your CPAN package'
author:
  - 'Shantanu Bhadoria <shantanu at cpan dott org>'
build_requires:
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  List::Util: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300038, CPAN::Meta::Converter version 2.132510'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-App-Command-dhmakeperl
no_index:
  directory:
    - t
    - xt
    - examples
    - corpus
    - inc
  package:
    - DB
provides:
  Dist::Zilla::App::Command::dhmakeperl:
    file: lib/Dist/Zilla/App/Command/dhmakeperl.pm
    version: 0.001
requires:
  Dist::Zilla::App: 0
  autodie: 0
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/shantanubhadoria/dist-zilla-app-command-dhmakeperl/issues
  homepage: https://metacpan.org/release/Dist-Zilla-App-Command-dhmakeperl
  repository: git://github.com/shantanubhadoria/dist-zilla-app-command-dhmakeperl.git
version: 0.001
x_contributors:
  - 'Shantanu <shantanu@cpan.org>'
